config/routes.rb
Rails.application.routes.draw do
  resources :twonts  
  #root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "twonts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twont.rb
class Twont < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/twonts_controller.rb
class TwontsController < ApplicationController
  before_action :set_twont, only: %i[ show edit update destroy ]

  # GET /twonts or /twonts.json
  def index
    @twonts = Twont.all
  end

  # GET /twonts/1 or /twonts/1.json
  def show
  end

  # GET /twonts/new
  def new
    @twont = Twont.new
  end

  # GET /twonts/1/edit
  def edit
  end

  # POST /twonts or /twonts.json
  def create
    @twont = Twont.new(twont_params)

    respond_to do |format|
      if @twont.save
        format.html { redirect_to twont_url(@twont), notice: "Twont was successfully created." }
        format.json { render :show, status: :created, location: @twont }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twont.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twonts/1 or /twonts/1.json
  def update
    respond_to do |format|
      if @twont.update(twont_params)
        format.html { redirect_to twont_url(@twont), notice: "Twont was successfully updated." }
        format.json { render :show, status: :ok, location: @twont }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twont.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twonts/1 or /twonts/1.json
  def destroy
    @twont.destroy

    respond_to do |format|
      format.html { redirect_to twonts_url, notice: "Twont was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twont
      @twont = Twont.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twont_params
      params.require(:twont).permit(:twont)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twonts_helper.rb
module TwontsHelper
end

app/views/home/_header.html.erb
<div class="navbar navbar-expand-lg navbar-primary bg-primary">
  <%= link_to 'Twonter',root_path, class:"navbar-brand text-white"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-auto">
      <li class="nav-item active">
        <%= link_to 'Home',root_path, class:"nav-link text-white "%>
      </li>
      <li class="nav-item">
      <a class="nav-link text-white ">Compose</a>
    </li>
      <li class="nav-item">
        <a class="nav-link text-white ">Profile</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0 position-absolute end-0">
      <ul class="navbar-nav mr-auto ml-auto">
        <li class="nav-item active">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </li>
        <li class="nav-item active">
          <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </li>
      </ul>
    </form>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Twonter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>

  <%= render 'home/header' %>
  <div class="container">
  <%= yield %>
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>


</html>

app/views/twonts/_form.html.erb
<%= form_with(model: twont) do |form| %>
  <% if twont.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(twont.errors.count, "error") %> prohibited this twont from being saved:</h2>

      <ul>
        <% twont.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :twont, style: "display: block" %>
    <%= form.text_area :twont %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/twonts/_twont.html.erb
<div class="card">
  <div class="card-body">
  <%= twont.twont %>
  <button type="button" class="btn btn-outline-primary position-absolute end-0">
    <%= link_to "Show", twont %>
  </button>
  </div>
</div>

app/views/twonts/edit.html.erb
<h1>Editing twont</h1>

<%= render "form", twont: @twont %>

app/views/twonts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="form-group">
  <textarea class="form-control" rows="3"></textarea>
    <%= link_to "New Twont", new_twont_path, class:"btn btn-info" %>
</div>

<div id="twonts">
  <% @twonts.each do |twont| %>
    <%= render twont %>
  <% end %>
</div>

app/views/twonts/new.html.erb
<h1>New twont</h1>

<%= render "form", twont: @twont %>

app/views/twonts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twont %>

<div>
  <%= link_to "Edit", edit_twont_path(@twont) %>
  <%= button_to "Delete" , @twont, method: :delete %>
</div>